options:
  max-warnings: 0
rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  nesting-depth:
    - 1
    - max-depth: 4
  leading-zero:
    - 1
    - include: true
files:
  include: 'src/**/*.scss'
  ignore:
    - 'src/main/steps/govuk/components/**'
