nodejs:
  cpuLimits: 500m
  cpuRequests: 100m
  memoryLimits: 1024Mi
  memoryRequests: 256Mi
  applicationPort: 3100
  aadIdentityName: idam
  ingressHost: idam-hmcts-access.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/idam/hmcts-access:latest'
  keyVaults:
    idam-idam:
      secrets:
        - AppInsightsInstrumentationKey
        - launchdarkly-sdk-key
        - redis-hostname
        - redis-port
        - redis-key
  environment:
    STRATEGIC_SERVICE_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net'
  autoscaling:
    enabled: true
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
